name = "csharp-card"
compatibility_date = "2024-01-01"

[env.production]
name = "csharp-card"

# Build configuration
[build]
command = "npm run build"
publish = "dist"

# Page rules
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
